prog = zinc component add -p kit -n

generate:
	$(prog) LocalPosition2 -d x:float32 -d y:float32 
	$(prog) LocalRotation2 -d x:float32 -d y:float32
	$(prog) LocalScale2    -d x:float32 -d y:float32
	$(prog) Velocity2      -d x:float32 -d y:float32 