// Package kit ...
// generated by zinc/MultiComponentDataTemplate. DO NOT EDIT.
package kit

import (
	"github.com/SirMetathyst/zinc"
)

// ZTimeService ...
var ZTimeService uint = uint(2184121015)

// ZTimeServiceData ...
type ZTimeServiceData struct {
	Min	int
	Sec	int
	
}

// TimeServiceComponent ...
type TimeServiceComponent struct {
	ctx  *zinc.ZContext
	data ZTimeServiceData
}

// RegisterTimeServiceComponentWith ...
func RegisterTimeServiceComponentWith(e *zinc.ZEntityManager) {
	x := NewTimeServiceComponent()
	ctx := e.RegisterComponent(ZTimeService, x)
	x.SetContext(ctx)
}

// RegisterTimeServiceComponent ...
func RegisterTimeServiceComponent() {
	x := NewTimeServiceComponent()
	ctx := zinc.Default().RegisterComponent(ZTimeService, x)
	x.SetContext(ctx)
}

// NewTimeServiceComponent ...
func NewTimeServiceComponent() *TimeServiceComponent {
	return &TimeServiceComponent{data: ZTimeServiceData{}}
}

func init() {
	RegisterTimeServiceComponent()
}

// SetContext ...
func (c *TimeServiceComponent) SetContext(ctx *zinc.ZContext) {
	if c.ctx == nil {
		c.ctx = ctx
	}
}

// SetTimeService ...
func (c *TimeServiceComponent) SetTimeService(data ZTimeServiceData) {
	c.data = data
}

// HasEntity ...
func (c *TimeServiceComponent) HasEntity(id zinc.ZEntityID) bool {
	return false
}

// TimeService ...
func (c *TimeServiceComponent) TimeService() ZTimeServiceData {
	return c.data
}

// DeleteEntity ...
func (c *TimeServiceComponent) DeleteEntity(id zinc.ZEntityID) error {
	return nil
}

// SetTimeServiceX ...
func SetTimeServiceX(e *zinc.ZEntityManager, data ZTimeServiceData) {
	v := e.Component(ZTimeService)
	c := v.(*TimeServiceComponent)
	c.SetTimeService(data)
}

// SetTimeService ...
func SetTimeService(data ZTimeServiceData) {
	SetTimeServiceX(zinc.Default(), data)
}

// TimeServiceX ...
func TimeServiceX(e *zinc.ZEntityManager) ZTimeServiceData {
	v := e.Component(ZTimeService)
	c := v.(*TimeServiceComponent)
	return c.TimeService()
}

// TimeService ...
func TimeService() ZTimeServiceData {
	return TimeServiceX(zinc.Default())
}